cardano-foundation/cardano-wallet-agda

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Timeline.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda, lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal, lib/customer-deposit-wallet-pure/generate-haskell.sh, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Everything.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Timeline.hs
This pull requests introduces a type `Timeline` type which is useful for storing a history of transactions and value transfers.
=> Add `Timeline` type

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/DeltaUTxO.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO.agda
This pull request adds comments on which entities are exported for the modules `DeltaUTxO` and `UTxO`.
=> Add module export comments

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/Tx.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
This pull request adds a function `computeValueTransfer` that computes how much value was spent from or received at a particular address.
=> Add `computeValueTransfer`

.buildkite/pipeline.yml, justfile
This pull request adds a check to CI that tests whether the generated `.hs` files have changed.
=> Detect changes to generated Haskell files

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set.agda
This pull request adds several functions to `Haskell.Data.Set`:
* `intersection`
* `Foldable`
=> Add `intersection` and `Foldable` to `Haskell.Data.Set`

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
This pull request adds several functions to `Haskell.Data.Map`:
* `update`
* `dropWhileAntitone` and `spanAntitone`
=> Add `update` and `spanAntitone` to `Haskell.Data.Map`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/InverseMap.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/List.agda, lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs, lib/customer-deposit-wallet-pure/haskell/Haskell/Data/InverseMap.hs, lib/customer-deposit-wallet-pure/haskell/Haskell/Data/List.hs
This pull request imports `foldl'` from `Data.List` and removes redefinitions.
=> Import `foldl'` 

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
This pull request adds various improvements to `Data.Map`. In particular:
* Fix definition of `prop-lookup-update`
* Add `prop-lookup-eq`
=> Improve `Haskell.Data.Map`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Read.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Read/Value.agda, lib/customer-deposit-wallet-pure/agda/Everything.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Core.lagda.md, lib/customer-deposit-wallet-pure/generate-haskell.sh, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Everything.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read/Value.hs, lib/customer-deposit-wallet-pure/haskell/Everything.hs
This pull request performs a few minor cleanups and additions.
* Move `Everything` module to the top level
* Add `Eq` instances to `Data.Map` and `Value`
* Add function `slotFromChainPoint`
* Move `subst` to `Haskell.Reasoning`
=> Minor cleanup

.buildkite/pipeline.yml, .hlint.yaml, .stylish-haskell.yaml, flake.nix, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/CollateralInputs.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/TxId.hs, scripts/buildkite/main/check-code-format.sh
- Add hlint 
- Add stylish-haskell
- Add hls
- Fix hlint hints
- Fix stylish-haskell issues
=> Harmonize haskell tooling

.gitignore, cabal.project, lib/cardano-wallet-read/cardano-wallet-read.cabal, lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
- Bump CHaP index 
- Bump ouroborus-consensus-cardano to 0.18
- Have haskell constraints only on project level
ADP-3422
=> [ADP-3422] Reduce haskell dependencies constraints

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Hash.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Type.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/Tx.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Write/Tx/Balance.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Hash.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Type.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs, lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs
This pull request adds Haddock documentation to almost all functions and types, except for a small number of modules.
=> Document almost all functions and types

lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Chain.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/TxId.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/TxIn.hs, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxSummary.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxSummary.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs
This pull request implements minor for the documentation and export lists of the Deposit Wallet and `Cardano.Wallet.Read`.
=> Documentation and export fixes for Deposit Wallet and `Cardano.Wallet.Read`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/Tx.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs
This pull request fixes the transpiled Haskell code for `applyTx` to retain common subexpressions. Apparently, transpilation of `let` expressions does not work very well yet.
=> Fix `applyTx` to keep common subexpressions in Haskell code

flake.lock, flake.nix, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Block.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Chain.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Eras.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Tx.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/InverseMap.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/PairMap.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maybe.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Word.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Word/Odd.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Core.lagda.md, lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.agda-lib, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
This pull request bumps the agda2hs transpiler to version 1.3.
=> Bump to agda2hs-1.3

lib/cardano-wallet-read/cardano-wallet-read.cabal, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Chain.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Chain/Genesis.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Chain/Point.hs, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Chain.agda
This pull request adds the data types `GenesisData` and `NetworkId` to `Cardano.Wallet.Read.Chain`.
=> Add `GenesisData` and `NetworkId` to `Cardano.Wallet.Read.Chain`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Maybe.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs, lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Maybe.hs
This pull request proves and postulates more properties for `UTxO`. This pull request also tidies up the `Haskell.Data.Map` module.
=> Expand properties in `UTxO`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
This pull request adds a function `getMaxCustomer` to the `AddressState`.
This pull request also simplifies the proofs for several lemmas for `AddressState`.
=> Add `getMaxCustomer` to `AddressState`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
This pull request changes the BIP32Path for the change address to `m / 1857' / 1815' / 0' / 1 / 0`.
This makes the path length equal to the path length of the customer addresses, whose path is `m / 1857' / 1815' / 0' / 0 / c` where `c : Word31` is the customer id.
=> Change change address path

lib/cardano-wallet-read/cardano-wallet-read.cabal, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/PParams.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/PParams/Mock.hs
This pull request adds a mock value for `PParams Conway` for testing.
=> Add `mockPParamsConway`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
This pull request proves the remaining postulates on `RollbackWindow` and improves the documentation. This pull request also adds `Eq` instances to `RollbackWindow` and `MaybeRollback`.
=> Prove remaining postulates on `RollbackWindow`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Core.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Core.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs, lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs
This pull request adds a function `Timeline.items` and uses it.
=> Add and use `Timeline.items`

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Word.agda
This pull request adds `Word32` to the Agda import module `Haskell.Data.Word`.
=> Add `Word32` to `Haskell.Data.Word`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
This pull request adds more `Show` instances in modules `Cardano.Wallet.Address.*`.
=> Add more `Show` instances

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map/Law.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
This pull request discharges the currently remaining `postulate`s involving `UTxO.restrictedBy`.
=> Prove `postulate` related to `UTxO.restrictedBy`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Timeline.agda, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Timeline.hs
This pull request improves the documentation of the module `Cardano.Wallet.Deposit.Pure.UTxO.UTxOHistory.Timeline`.
=> Improve documentation of `UTxOHistory.Timeline`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set/Law.agda, lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda
This pull request proves a number of properties about `Data.Set`. In particular, we prove that
* `Set.intersection` and `Set.union` form a [Boolean Algebra](https://en.wikipedia.org/wiki/Boolean_algebra)
* `Set.isSubsetOf` is a [partial order](https://en.wikipedia.org/wiki/Partially_ordered_set#Partial_order)
=> Prove properties from Boolean Algebra about `Data.Set`

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set/Law.agda
This pull request proves additional properties of `Set.difference`.
=> Prove more properties for `Set.difference`

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.agda, lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Value.agda, lib/customer-deposit-wallet-pure/agda/Everything.agda, lib/customer-deposit-wallet-pure/agda/Implementation.agda, lib/customer-deposit-wallet-pure/agda/Specification.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Value.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Wallet/Payment.lagda.md, lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs
This pull request updates the specification of the Deposit Wallet.
This pull request
* Elaborates the specification of some concepts that we depend on, such as `Value`.
* Prepares the use of separate files for the specification.
* Moves the `Implementation` closer to the specification.
=> Update `Specification` structure

lib/customer-deposit-wallet-pure/agda/Everything.agda, lib/customer-deposit-wallet-pure/agda/Implementation.agda, lib/customer-deposit-wallet-pure/agda/Specification.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Cardano.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Cardano/Tx.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Cardano/Value.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Common.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Wallet/Payment.lagda.md
This pull request is about modularizing the `Specification`, such that less relevant concepts are imported, and the main document can focus on the specific features of the Deposit Wallet.
=> Modularize the `Specification`

lib/customer-deposit-wallet-pure/agda/Implementation.agda, lib/customer-deposit-wallet-pure/agda/Specification.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Cardano.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Cardano/Chain.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Cardano/Tx.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Wallet/UTxO.lagda.md
This pull request updates the specification of the deposit wallet.
Specifically, we update the discussions on
* `TxHistory`
=> Update specification of `getCustomerHistory`

lib/customer-deposit-wallet-pure/agda/Implementation.agda, lib/customer-deposit-wallet-pure/agda/Specification.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Common.lagda.md, lib/customer-deposit-wallet-pure/agda/Specification/Wallet/Payment.lagda.md
This pull request updates the specification of the deposit wallet.
Specifically, we update the discussions on
* `createPayment`
=> Update specification of `createPayment`

lib/cardano-wallet-read/CHANGELOG.md, lib/cardano-wallet-read/cardano-wallet-read.cabal, lib/cardano-wallet-read/haskell/Cardano/Read/Ledger.hs, lib/cardano-wallet-read/haskell/Cardano/Wallet/Read.hs
This pull request polishes the documentation of the `cardano-wallet-read` package in preparation for a release to [CHaP](https://chap.intersectmbo.org/).
=> Polish documentation of `cardano-wallet-read`

lib/customer-deposit-wallet-pure/agda/Specification.lagda.md
This commit suggests a way to "strengthen" the introduction and provide more details about the properties we want to prove, and why we want to do this.
=> Provide more details on goals and requirements in the introduction

.gitignore, cabal.project, flake.lock, flake.nix, fourmolu.yaml, justfile, lib/cardano-wallet-read/cardano-wallet-read.cabal, lib/cardano-wallet-read/haskell/Cardano/Read/Ledger/Block/HeaderHash.hs, lib/cardano-wallet-read/haskell/Cardano/Read/Ledger/Block/Txs.hs, lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal, scripts/buildkite/main/attic-cache.sh, scripts/bump-constraints.sh
- Add a script to extract dependency constraints from a freeze file
- Bump project index-state
- Remove unneeded dependencies
- Add plutus-core dependency on project level :shrug: 
#156
=> Bump cardano dependencies to match node 10.2.1
