lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxSummary.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/ValueTransfer.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxSummary.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/ValueTransfer.hs

This pull request moves the types `ValueTransfer` and `TxSummary` to separate modules in order to export them.

Move `ValueTransfer` and `TxSummary` to separate modules

---

lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal

This pull request constrains version numbers for the dependencies of the `customer-deposit-wallet-pure.cabal` package.

Constrain version numbers for dependencies

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Word.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Word/Odd.agda
lib/customer-deposit-wallet-pure/agda2hs-rewrites.yaml
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Word/Odd.hs

This pull request adds a module `Cardano.Wallet.Address.BIP32_Ed25519` which imports / `postulate`s address derivation functionality from `cardano-crypto`.

Add `BIP32_Ed25519` modules

---

justfile
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs

This pull request fixes a few minor issues:
* Update generated `Cardano/Wallet/Address/BIP32_Ed25519.hs`
* Add `*.lagda.md` specification to `.cabal` file
* Add command `clean` to the `justfile` in order to delete `*.agdai` files

Minor fixes

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Hash.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Hash.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request imports the `Blake2b_224` and `Blake2b_256` hash functionalities from the `cardano-crypto-class` package.

Add Blake2b_224 and Blake2b_256

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request uses the actual BIP32_Ed25519 derivation scheme instead of a mock scheme in the definition of `AddressState.createAddress`. The proofs carry through if we postulate strong enough injectivity properties of the `deriveXPubSoft` function.
* The mapping `XPub → Address` is still a mock version and does not yet use the actual binary representation of Cardano addresses.

Use BIP32_Ed25519 in `createAddress`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request
* adds a function `mkEnterpriseAddress` that maps a payment `XPub` to an enterprise address
* uses this function in `deriveAddress`.
* With this pull request, the `AddressState` type can be used to generate addresses which are (should be) spendable on mainnet.

Add and use `mkEnterpriseAddress`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request adds a function `getBIP32Path` that returns a standardized `BIP32Path` for the addresses managed by `AddressState`.
We also prove a lemma that relates `isOurs` to the success of `getDerivationPath`:
```agda
@0 lemma-getDerivationPath-Just
: ∀ (s : AddressState)
(addr : Address)
→ isOurs s addr ≡ True
→ ∃ (λ path → getDerivationPath s addr ≡ Just path)
```

Add `getBIP32Path`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32.hs

This pull request adds `Eq` and `Ord` class instances for `BIP32Path` so that this type can be used in a container type such as `Data.Set.Set`.

Add `Eq` and `Ord` instances for `BIP32Path`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Write/Tx/Balance.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Core.lagda.md

This pull request adds a module `Haskell.Reasoning.Bool`.
This modules adds lemmas that relate the operations `&&`, `||` and `not` on the `Bool` data type to the logical connectives `⋀`, `⋁`, and `¬` from the metatheory. This simplifies reasoning with predicates of the form `b ≡ True`, enabling proofs about Haskell functions such as `filter` or `any`.
This pull request removes a couple of ad-hoc lemmas about logical connectives that are either obsolete or subsumed by the new module.

Add `Haskell.Reasoning.Bool`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Read.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read.hs

This pull request adds an initial implementation of the `UTxOHistory` type, copied from https://github.com/cardano-foundation/cardano-wallet/blob/eafaf8f522b1536f0ab6b9434d0471b9a2f6701e/lib/wallet/src/Cardano/Wallet/DB/Store/UTxOHistory/Model.hs .

Add initial implementation of `UTxOHistory`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/InverseMap.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/InverseMap.hs

This pull request adds a type synonym `InverseMap` and uses it in the implementation of `UTxOHistory`.
In this way, we can simplify the helper functions used in the implementation of `UTxOHistory.Core`. It turns out that they can be subsumed by the function
* `InverseMap.insertManyKeys`
* `InverseMap.difference`

Add `InverseMap` type and use it in `UTxOHistory`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/PairMap.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/PairMap.hs

This pull request implements a type `PairMap` which is essentially a map
```agda
PairMap a b v = Map (a × b) v
```
However, this type provides efficient lookup functions
```agda
lookupA : a → PairMap a b v → Map b v
lookupB : b → PairMap a b v → Map a v
```
In database terminology, this type stores rows of the form `a × b × v` and maintains an index on both the first column `a` and the second column `b`.
The datatype is implemented by storing two nested maps `Map a (Map b v)` and `Map b (Map a v)`. The `invariant-equal` expresses that these maps contain the same elements, and we formally prove that this invariant holds.

Implement `PairMap` type

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Everything.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/Tx.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/List.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/List/Prop.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/PairMap.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/List.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/PairMap.hs

This pull request implements a type `TxHistory` which represents a history of transactions. This data type supports the following efficient queries:
* `getAddressHistory` — Return a list of transactions that involve a given address.
* `getValueTransfers` — Given a range of slots, return the total `ValueTransfer` by address.

Implement `TxHistory`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Implementation.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure.agda
lib/customer-deposit-wallet-pure/agda/Everything.agda
lib/customer-deposit-wallet-pure/agda/Specification.lagda.md

This pull request adds a module `Cardano.Wallet.Deposit.Implementation`. This module uses the implemented functions to defines two values `operations` and `properties` that have types which are imported from the specification document. If these values are completely defined and the compiler accepts them, this means we have an implementation which satisfies the specification.
Currently, the `properties` still contains some unsolved metavariables, i.e. incomplete proofs. However, the proof for `prop-createPayment-not-known` is complete.
* This pull request is mainly an exercise in how to combine implementation and specification. The purpose of a specification is to be human-readable, while the focus of an implementation is to contain enough details to be machine-executable. This brings some …

Partially match the `Specification` with the implementation

---

fourmolu.yaml
lib/customer-deposit-wallet-pure/generate-haskell.sh
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Hash.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxSummary.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read/Value.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Write/Tx/Balance.hs
lib/customer-deposit-wallet-pure/haskell/Everything.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/List.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/InverseMap.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/PairMap.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maybe.hs

This pull request adds a `fourmolu` pass on the Haskell code that was generated by `agda2hs` in order to improve readability. (I find some of the indentation choices of the `haskell-src-exts` pretty printer questionable.)

Automatically use `fourmolu` on generated Haskell code

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Read/Value.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read/Value.hs

This pull request fixes a warning about name-shadowing in `Cardano.Wallet.Deposit.Read.Value`.

Fix name shadowing in `Cardano.Wallet.Deposit.Read.Value`

---

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Data/Maps/Timeline.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request exposes the module `Data.Maps.Timeline` in the package for outside use.
We also export a function `Data.Maps.Timeline.insert` that inserts a single item only.

Expose `Data.Maps.Timeline`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Read.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Tx.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString/Short.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maybe.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Read.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Read/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Read/Tx.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/ByteString/Short.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maybe.hs

This pull request changes `Cardano.Wallet.Deposit` to depend on the
Haskell module `Cardano.Wallet.Read.Address` from the
`cardano-wallet-read` package.
At the moment, this dependency is mocked, it will be replaced by the
real thing later.
This pull request also adds
* A module `Haskell.Data.ByteString.Short` for the `ShortByteString` type.
* To the module `Haskell.Data.Maybe`
* The function `fromJust` with proof obligation
* Additional properties relating to injectivity

Depend on mocked `Cardano.Wallet.Read.Address`

---

lib/cardano-wallet-read/cardano-wallet-read.cabal
lib/cardano-wallet-read/haskell/Cardano/Read/Ledger/Block/BlockNo.hs
lib/cardano-wallet-read/haskell/Cardano/Read/Ledger/Block/SlotNo.hs
lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx.hs
lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/CollateralInputs.hs
lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/TxId.hs
lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/TxOut.hs
lib/cardano-wallet-read/test/Cardano/Wallet/Read/Tx/TxIdSpec.hs
lib/cardano-wallet-read/test/Cardano/Wallet/Read/Tx/TxOutSpec.hs

This pull request fixes various small issues with the `cardano-wallet-read` package.
It also fixes a larger issue — the definition of `utxoFromEraTx` was wrong. 😳 It should be moved to the `.agda` files and accompanied with some proof that making a basic transaction with outputs and applying it to the `UTxO` has the same effect as adding the outputs directly.

Fix small issues with `cardano-wallet-read`

---

lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/ScriptValidity.hs

This pull request adds a COMPLETE pragram to the `IsValidC` pattern synonym in order to enable checking for incomplete pattern matches in dependent code.

Add COMPLETE pragma to `IsValidC`

---

.buildkite/pipeline.yml
justfile

This pull request changes CI such that
* The transpilation of `.agda` files is a separate step from the compilation of `.hs` files.
* The `.hs` files are compiled with the `-frelease` flag.
* As the codebase is small and should compile quickly, there is no need to introduce `block` steps in the Buildkite pipeline — there is no secondary CI.

Separate Haskell build step and add `-frelease` flag

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Read.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Block.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Ord.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs

This pull request adds a type `RollbackWindow`, which represents a time interval between `finality` and `tip`.
The idea is that a `rollForward` can be used to move the `tip` forward, while `rollBackward` can be used to roll the `tip` backwards — but only up to `finality`. The `finality` indicates the point until which rollbacks are possible — older data has been discarded by using `prune`.
The boundaries of the interval are inclusive, as the properties `prop-finality-member` and `prop-tip-member` demonstrate.
This pull request also changes the `UTxOHistory` type to make use of the `RollbackWindow` type. Importantly, the helper functions `constrainingAppendBlock`, `constrainingRollback`, and `constrainingPrune` that distinguish different cases are replaced by their corresponding `case` …

[ADP-3344] Add type `RollbackWindow`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda

This pull request adds the `union` function and some of its properties to `Data.Set` and `Data.Map`.
Importantly, in order to simplify reasoning about `Map` and sets `ℙ`, we also add two postulates:
* Two `Map` are propositionally equal if `lookup` gives the same result
```agda
Map.prop-equality
: ∀ {m1 m2 : Map k a}
→ (∀ (key : k) → lookup key m1 ≡ lookup key m2)
→ m1 ≡ m2
```
* Two `Map` are propositionally equal if `member` gives the same result
```agda
Set.prop-equality
: ∀ {s1 s2 : ℙ a}
→ (∀ (x : a) → member x s1 ≡ member x s2)
→ s1 ≡ s2
```
I have decided against using Setoids, as this will complicate equational reasoning unnecessarily. Instead, we use `≡` and enjoy the fact that it can be used for substitution in *any* context, not just for contexts that preserve setoid equality.

Add `union` to `Data.Set` and `Data.Map`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/Tx.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs

This pull request fixes the implementation of `DeltaUTxO` such that `append x y : DeltaUTxO` will apply `x` *after* `y`, i.e. the order of application is right-to-left.
In order to show that the new implementation does what we want, I have now proved the following property which relates `append` to `apply`:
```agda
prop-apply-append
: ∀ (x y : DeltaUTxO) (utxo : UTxO)
→ Set.intersection (dom (received y)) (dom utxo) ≡ Set.empty
→ apply (append x y) utxo ≡ apply x (apply y utxo)
```
In other words, if `utxo` and `y` have disjoint transaction inputs, then applying `append x y` is the same as first applying `y` and then applying `x`. As `TxIn` are globally distinct, the preconditions always holds at usage sites.
However, as this property is not unconditionally true when duplicate `TxIn` are …

Fix `DeltaUTxO.append`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs

This pull request fixes the implementation of `excludingD` and proves that the new implementation satisfies the following expected property:
```agda
-- | The 'UTxO' returned by 'excludingD' agrees
-- with the application of the delta to the input 'UTxO'.
--
prop-apply-excludingD
: ∀ {txins : Set.ℙ TxIn} {u0 : UTxO}
→ let (du , u1) = excludingD u0 txins
in  apply du u0 ≡ u1
```
Somewhat unrelatedly, this pull request also adds minor conveniences to the `DeltaUTxO` type.

Fix `excludingD` and prove `prop-apply-excludingD`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Maybe.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Maybe.hs

This pull request adds a module `Data.Map.Maybe`. This module adds functions for the `Maybe` type that are analogous to the functions in `Data.Map`.
This addition makes proofs of properties of `Map` more transparent, as we base them on the isomorphism `Map k a = k → Maybe a`.
We use this right away to prove the property
```agda
prop-excluding-intersection
: ∀ {x y : Set.ℙ TxIn} {utxo : UTxO}
→ (Set.intersection x y) ⋪ utxo ≡ (x ⋪ utxo) ∪ (y ⋪ utxo)
```

Add `Data.Maps.Maybe`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Maybe.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs

This pull request fixes the definition of `receiveD` for duplicate `TxIn`s (which do not occur at usage sites, but still) and proves the two defining properties of `receiveD`.

Prove properties of `receiveD`

---

lib/agda2hs-fixer/haskell/Language/Agda2hs/Agda/Parser.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Documentation.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Haskell/Types.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/InverseMap.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request adds documentation, primarily for functions on the `UTxO` and `TxHistory` types.
This pull request also fixes `agda2hs-fixer` to parse Agda identifiers whose type signature starts on the next line.
* Documentation for data types and properties has not been implemented yet.

Document `UTxO` and `TxHistory` functions

---

lib/agda2hs-fixer/haskell/Language/Agda2hs/Agda/Parser.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Haskell/Parser.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Haskell/Types.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxSummary.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxSummary.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/PairMap.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request improves the `adga2hs-fixer` utility to also include add Haddock documentation for data types.
Specifically, this pull request adds support for `data`, type synonyms, `data` declarations, and `record` types.

Implement documentation for types

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxSummary.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Chain.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Maybe.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxSummary.hs

This pull request changes the functionality of the `TxHistory` module to make use of the `TxSummary` type.
* Added: `getValueTransferInRange` (with the semantics of the old `getValueTransfers`)
* Changed: `getAddressHistory`, `getValueTransfers`, `rollForward`
* The function `getAddressHistory` does not yet return the transactions by `Slot`
* The `TxHistory` type does not yet keep track of the order in which transactions appear in a block.

Improve `TxHistory` to use `TxSummary`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Experimental.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Block.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Chain.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Tx.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString/Short.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Maybe.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Core.lagda.md

This pull request drops the dependency on the [Agda `stdlib`](https://github.com/agda/agda-stdlib) for the sake of improving compile-time performance. It also foreshadows some changes in `agda2hs` version 1.3

Drop Agda `stdlib`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Implementation.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Experimental.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/ByteString/Short.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Experimental.hs

This pull request adds support for `Testnet` addresses in the `AddressState`. Specifically, the address state can be initialized for a particular `Network`, and all addresses will be generated for this network.

Support `Testnet` addresses in `AddressState`

---

lib/agda2hs-fixer/haskell/Language/Agda2hs/Agda/Parser.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Agda/Types.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Documentation.hs
lib/agda2hs-fixer/haskell/Language/Agda2hs/Haskell/Types.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Maybe.hs

This pull request adds support for documenting properties in the generated Haddock documentation.
Specifically, properties that have been proven about the Haskell-in-Agda code are now added to the Haddock documentation if they have a Haddock-style comment.
Function `excluding`:
Source code of a property with Haddock-style comment:
```agda
-- |
-- Excluding two sets of 'TxIn's can be done in either order.
--
prop-excluding-sym
: ∀ {x y : Set.ℙ TxIn} {utxo : UTxO}
→ x ⋪ (y ⋪ utxo) ≡ y ⋪ (x ⋪ utxo)
--
prop-excluding-sym {x} {y} {utxo} = [… proof here …]
```
Rendering:
* The parsers are very rudimentary — the type signature of a property is currently recognized by the fact that it ends with a single-line comment `--`. I like this style because it helps visually with the Agda code as well, but …

Support Haddock documentation for Agda properties

---

lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Data/Maps/InverseMap.hs
lib/customer-deposit-wallet-pure/haskell/Data/Maps/PairMap.hs

This pull request exposes the `PairMap` and `InverseMap` types in order to allow downstream code to implement new queries on `TxHistory`. We may want to move these queries back into the codebase here, but that's for another time.

Expose `PairMap` and `InverseMap`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request proves an important property about `UTxOHistory`, namely that `rollBackward` cancels `rollForward`:
```agda
prop-rollBackward-rollForward-cancel
: ∀ (u : UTxOHistory) (du : DeltaUTxO) (slot1 : Slot) (slot2 : SlotNo)
→ (slot1 < WithOrigin.At slot2) ≡ True
→ rollBackward slot1 (rollForward slot2 du u)
≡ rollBackward slot1 u
```
In other words, this property tells us that the type `UTxOHistory` is suitable for rolling back the `UTxO` set.
Together with the design that rolling back "into the future" does nothing, this property allows us to straighten any sequence of roll forwards and roll backwards into a sequence of roll forwards.

Prove that `rollForward` cancels `rollBackward` for `UTxOHistory`

---

lib/agda2hs-fixer/haskell/Language/Agda2hs/Agda/Types.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Read/Value.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs

This pull request
* postulates instances of `IsLawfulSemigroup Value` and `IsLawfulMonoid Value`
* deduces instances of `IsLawfulSemigroup ValueTransfer` and `IsLawfulMonoid ValueTransfer`
* postulates that `Value` is a commutative semigroup
* decudes that `ValueTransfer` is a commutative semigroup

Add monoid and semigroup laws to `Value` and `ValueTransfer`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request fixes an off-by-one error in `fromXPubAndCount`.
I had skipped this in the initial implementation because generating the initial list of customers is not entirely trivial: The simple expression `fromEnumTo 0 (pred knownCustomerCount)` will not be accepted by the compiler — we have to convince the compiler that `pred` is not applied to `0`.

Fix off-by-one error in `fromXPubAndCount`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs

This pull request renames `UTxOHistory.empty` to `UTxOHistory.fromOrigin`.

Rename `empty` to `fromOrigin`

---

lib/cardano-wallet-read/cardano-wallet-read.cabal
lib/cardano-wallet-read/haskell/Cardano/Read/Ledger/Block/SlotNo.hs
lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx.hs
lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Tx/Validity.hs

This pull request implements and exports a function
```hs
getValidityInterval :: forall era. IsEra era => Tx era -> ValidityInterval
```
in `Cardano.Wallet.Read`. This function returns a uniform `ValidityInterval` for transactions in all eras.

Add `getValidityInterval` to `Cardano.Wallet.Read`

---

lib/agda2hs-fixer/haskell/Language/Agda2hs/Documentation.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Maybe.hs

This pull request adds the prefix `p:` to the anchors for properties in the Haddock documentation. This brings the anchor names in line with the naming convention for anchors in Haddock, where `v:` prefixes values and `t:` prefixes types.

Add `p:` prefix to property anchors in Haddock

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Timeline.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Everything.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Timeline.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs

This pull request adds a data type `TimelineUTxO` which represents a timeline of changes to the `UTxO`. This type is similar to `UTxOHistory`, but does not involve a `RollbackWindow`.
The intention is that the type `UTxOHistory` will be built on top of the type `TimelineUTxO`.

Add `TimelineUTxO`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request exports the function `isChangeAddress` for the `AddressState` type and also adds a documentation property `isOurs`.

Export `isChangeAddress`

---

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map/Def.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map/Law.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Maybe.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set.agda
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Maybe.hs

This pull request proves the fact that the function `Data.Map.union` is symmetric if the maps are disjoint:
```agda
prop-union-sym
: ∀ {ma mb : Map k a}
→ disjoint ma mb ≡ True
→ union ma mb ≡ union mb ma
```
In turn, we define
```agda
disjoint : Map k a → Map k b → Bool
disjoint m1 m2 = null (intersection m1 m2)
```
and `intersection`, and add helper proofs.

Prove `prop-union-sym` for `Data.Map`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request adds derived instances of `Show` for several data types. In this way, the combined state of the Deposit Wallet can also have a `Show` instance.

Add derived instances for `Show`

---

lib/agda2hs-fixer/haskell/Language/Agda2hs/Agda/Parser/ExportList.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519.agda
lib/customer-deposit-wallet-pure/agda/Everything.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Cardano/Crypto/Wallet.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Cardano/Crypto/Wallet.hs

This pull request changes the import of the Haskell module `Cardano.Crypto.Wallet` to be (more) vanilla, where we postulate the functions (mostly) as exported, instead of trying to massage the module functions.
The module `Cardano.Wallet.Address.BIP32_Ed25519` then imports the `Haskell.Cardano.Crypto.Wallet` and does perform a massage.

Change import of `Haskell.Cardano.Crypto.Wallet` to be vanilla

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/Encoding.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Cardano/Crypto/Wallet.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/Encoding.hs

This pull request fixes the mapping from `XPub` to `Addr` by hashing the public key rather than the full extended public key.

Fix `keyHashFromXPub` to use `rawPublicKeyFromXPub`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/RollbackWindow.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Timeline.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/RollbackWindow.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Core.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxOHistory/Timeline.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request adds a pragma
```agda
{-# FOREIGN AGDA2HS
{-# LANGUAGE StrictData #-}
#-}
```
to long-lived data structure in order to control memory usage.

Add `StrictData` to long-lived data structures

---

lib/cardano-wallet-read/haskell/Cardano/Wallet/Read/Eras/EraValue.hs
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/TxHistory/Type.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/Tx.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/PairMap.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/TxHistory/Type.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/Tx.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/ValueTransfer.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/PairMap.hs

- Add StrictData to `TxHistory`
- Add StrictData to `PairMap`
- Add StrictData to `ResolvedTx`
- Add StrictData to `EraValue`
- Add StrictData to `ValueTransfer`
Some of these types appear unused from the deposit wallet (like this `TxHistory`), but presumably deserve increased strictness anyway.
Related to https://github.com/cardano-foundation/cardano-wallet/issues/4876, but these changes didn't seem to be needed to fix the issue

Add more `StrictData` annotations

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

This pull request adds documentation about our continuous integration (CI) approach to `CONTRIBUTING.md`. It also adds a build badge to the `README.md`.
Resolves #118

Add documentation for continuous integration (CI)

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Address/BIP32_Ed25519/Encrypted.agda
lib/customer-deposit-wallet-pure/agda/Everything.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Cardano/Crypto/Wallet.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Address/BIP32_Ed25519/Encrypted.hs
lib/customer-deposit-wallet-pure/haskell/Haskell/Cardano/Crypto/Wallet.hs

This pull request implements a data type `EncryptedXPrv` that captures the notion of a private key that was encrypted in memory for an extra layer of protection against eavesdroppers.
The present implementation is essentially an indirection over `Cardano.Crypto.Wallet` from the `cardano-crypto` package, and makes explicit some assumptions and properties from that package.

Add `Cardano.Wallet.Address.BIP32_Ed25519.Encrypted`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs

This pull request adds properties of `DeltaUTxO` to the documentation of the Haskell code. This pull request also performs a small cleanup by using `UTxO.disjoint` in preconditions, as opposed to the more verbose `Set.intersection` of the domains.

Add `DeltaUTxO` properties to documentation

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map/Def.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map/Law.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/PairMap.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Set.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Reasoning/Bool.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/DeltaUTxO.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/UTxO/UTxO.hs

This pull request adds a predicate
```agda
fits : DeltaUTxO → UTxO → Bool
fits du u =
Set.isSubsetOf (excluded du) (dom u)
&& UTxO.disjoint (received du) u
```
that describes whether a given `DeltaUTxO` "fits" on top of a given `UTxO` by not removing transaction inputs that are not there, and by not adding transaction inputs that are already there. These conditions will always be satisfied when the `DeltaUTxO` is coming from a new block, but we have to make them explicit.
This predicate will be useful as a precondition for properties of `UTxOHistory`.

Add predicate `DeltaUTxO.fits`

---

lib/customer-deposit-wallet-pure/agda/Haskell/Data/Map/Law.agda
lib/customer-deposit-wallet-pure/agda/Haskell/Data/Maps/Timeline.agda
lib/customer-deposit-wallet-pure/haskell/Haskell/Data/Maps/Timeline.hs

This pull request adds properties to the `Data.Maps.Timeline` data type — some with proofs, as postulates for now. It also polishes the documentation of the generated Haskell module.

Add properties to `Data.Maps.Timeline`.

---

flake.lock
flake.nix

This pull request bumps the `agda2hs` dependency to `v1.3`.

Bump `adga2hs` to version 1.3

---

lib/customer-deposit-wallet-pure/agda/Implementation.agda
lib/customer-deposit-wallet-pure/agda/Specification.lagda.md
lib/customer-deposit-wallet-pure/agda/Specification/Cardano.lagda.md
lib/customer-deposit-wallet-pure/agda/Specification/Common.lagda.md
lib/customer-deposit-wallet-pure/agda/Specification/Wallet/UTxO.lagda.md

This pull request updates the specification of the mapping between `Customer` and `Address` to match what we have implemented.
This pull request does not yet address the sections on
* `TxHistory`
* `createPayment`

Update specification of mapping `Customer` → `Address`

---

.buildkite/pipeline.yml
justfile
lib/containers/agda/EverythingContainers.agda
lib/containers/agda/Haskell/Data/Map.agda
lib/containers/agda/Haskell/Data/Map/Law.agda
lib/containers/agda/Haskell/Data/Map/Maybe.agda
scripts/agda2hs-libraries.sh
scripts/check-agda.sh

This pull request adds continuous integration for the local `containers.agda-lib` library. We do not generate Haskell code, but we do need to typecheck the proofs.

Add CI for `containers`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Experimental.agda
lib/customer-deposit-wallet-pure/agda/Implementation.agda
lib/customer-deposit-wallet-pure/agda/Specification.lagda.md
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Experimental.hs

This pull request changes the specification and implementation to use `fromXPubAndCount` again, because that is more readily understandable to users.
After reworking the specification, the only property that can tell the difference between `fromXPubAndCount` and `fromXPubAndMax` is
```agda
prop-listCustomers-fromXPubAndCount-range
: ∀ (c : Customer) (xpub : XPub) (count : Word31)
→ knownCustomer c (fromXPubAndCount xpub count)
≡ (0 <= c && c < count)
```
The other parts of the specification do not require changes, basing them on `knownCustomer` was an effective move.

Change to `fromXPubAndCount`

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Experimental.agda
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs

This pull request removes exports of the `createAddress` function, as this function is no longer used by the specification. However, it is still used internally.

Remove `createAddress` exports

---

lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address.agda
lib/customer-deposit-wallet-pure/agda/Cardano/Wallet/Deposit/Pure/Address/Customer.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Address/Customer.hs
lib/customer-deposit-wallet-pure/haskell/Cardano/Wallet/Deposit/Pure/Experimental.hs

This pull request splits off a module `Cardano.Wallet.Deposit.Pure.Address.Customer` which contains the derivation path logic for customer and change addresses, including proofs.

Split address derivation for customers into separate module

---

lib/customer-deposit-wallet-pure/agda/Data/Function.agda
lib/customer-deposit-wallet-pure/agda/Data/Function/Law.agda
lib/customer-deposit-wallet-pure/agda/Data/List/Law.agda
lib/customer-deposit-wallet-pure/customer-deposit-wallet-pure.cabal
lib/customer-deposit-wallet-pure/haskell/Data/Function/Law.hs
lib/customer-deposit-wallet-pure/haskell/Data/List/Law.hs

This pull request adds a proof to `Data.List.Law` that `map` preserves `isDeduplicated` for injective functions.
```agda
prop-isDeduplicated-map
: ∀ ⦃ _ : Eq a ⦄ ⦃ _ : IsLawfulEq a ⦄
⦃ _ : Eq b ⦄ ⦃ _ : IsLawfulEq b ⦄
→ ∀ (f : a → b) → Injective f
→ ∀ (xs : List a)
→ isDeduplicated xs ≡ True
→ isDeduplicated (map f xs) ≡ True
```
In order to prove this property, it was easier to rework the definition `isDeduplicated` to be primitively recursive. The previous definition `isDeduplicated xs = (nub xs == xs)` is now a proven property rather than a definition.

Prove that `map` preserves `isDeduplicated` for injective functions
